all:
	cd common;make;cd ..
	cd http;make;cd ..
	cd main;make;cd ..
	cd net;make;cd ..
	cd work;make;cd ..
#	$(CXX) -o $(SERVER_ROOT)/obj/main $(SERVER_ROOT)/obj/*.o
install:
	cd common;make install;cd ..
	cd http;make install;cd ..
	cd main;make install;cd ..
	cd net;make install;cd ..
	cd work;make install;cd ..

clean:
#	make -f makefile.obj clean;
	cd common;make clean;cd ..
	cd http;make clean;cd ..
	cd main;make clean;cd ..
	cd net;make clean;cd ..
	cd work;make clean;cd ..

